import os
from pytest_test_marker.manifest import ManifestFile
from pytest_test_marker.mark import CollectionModifier


pytest_plugins = ["pytester"]
plugin_name = "pytest-test-marker"

marker_file = os.getenv('PYTEST_MARKER_FILE', 'tests/test_data/marks.yml')
manifest = ManifestFile(marker_file)
marks = manifest.get_marks()


def add_custom_marks_to_pytest_config(config):
    for marker in marks.keys():
        ini_line = "{}: generated by {}".format(marker,
                                                plugin_name)
        config.addinivalue_line('markers', ini_line)


def apply_marks_to_collected_tests(items):
    modifier = CollectionModifier(items, marks)
    modifier.apply_markers()


def pytest_configure(config):
    add_custom_marks_to_pytest_config(config)


def pytest_collection_modifyitems(config, items):
    apply_marks_to_collected_tests(items)
