from pytest_test_marker.manifest import ManifestFile
from pytest_test_marker.mark import (CollectionModifier,
                                     MarkDefinition)


pytest_plugins = ["pytester"]
plugin_name = "pytest-test-marker"

manifest = ManifestFile('tests/test_data/marks.yml')
marks = manifest.get_marks()


def pytest_configure(config):
    for marker in marks.keys():
        ini_line = "{}: generated by {}".format(marker,
                                                plugin_name)
        config.addinivalue_line(ini_line)


def pytest_collection_modifyitems(config, items):
    modifier = CollectionModifier(items, marks)
    modifier.apply_markers()
