name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: python:3

    steps:
      - uses: actions/checkout@v2

      - name: Linting and Unit Tests
        run: |
          pip install tox
          tox
