name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      pytest-test-marker:
        python-version: ['2.7', '3.6', '3.7', '3.8']

    steps:
      - uses: actions/checkout@v2

      - name: Linting and Unit Tests
        uses: actions/setup-python@v2
        with:
          python-version: ${{ pytest-test-marker.python-version }}
      - run: |
          pip install tox
          tox
