name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Linting and Unit Tests
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          pip install tox
          tox
